before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: wn/0FSpvgkl822SH8J+up1ExpqM/RNUN55lThmYlbEvl7fUdDpG/xRup2OZx54OGYd/uVWDkt+UBiI9tnOngOmDGzUPlWkfEiW+sVgjC0qOlb7nUkgdnz/T74501LeACPlbSf5KuFq0bsZsas4rNOqiraAdolBoyWhQRQYAzh/prcTqPZrL1Psjg7XKqEa+U98wFLd+aFKdZY8Ba/+Xa+o8voTpProJTwm1f56hIGOnf4kQGpfz+liV9ho4s5UdwwSmQztxD5MTsIEctEburMNbzo638vpxpbMLNSz0NvLQnvJHpHnQIaXKA3JiDVm5TzswqtUl8PP6BEjOuzAWcQ0rrNIReLEajKhF/0ePDprmAgWaYNkrxiV8jHbDHwW/M92Hrvxfo6SAvb4DjtN/Shc3Bm4Sr+/rImOu3qgCuZY2iHZ4FCG0/2y+/hmUf7qKus3kamLHEbipCvlO+Ky5emTbU8F3poH50OUnRYsf/dMHnycHgiAoopA7bJ5k1P1l60wvsbaDVUGt7p9bIAfMMWH3OJh+wdo/czkTuycEjZsOGJ3+jaCv/AqjuIzn6JHwrEZDeRzw0lcMLsc7TguDNbIcpm/etRiA+8224Wd+QS0O/Od4DfQmkyU0y+hV/vGy4hT4nGAMEhLc9PRdgc62nxaerESM1aShAmYRaW6baCY8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
